name: Atualizar dados BRCMX

on:
  schedule:
    - cron: '0 3 1 * *'  # Executa todo dia 1 do mês às 03:00 UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🔧 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🧪 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Rodar pipeline de atualização
        run: |
          python update_pipeline.py